openstack_network_id: 2d8bb3fc-fd89-49dc-84ea-5d304e372c87
ni_mon:
  host: http://141.223.181.149:8383           # Configure here to interact with a monitoring module
  measurements_uri: http://141.223.181.149:8383/measurements
  measurement_types_uri: http://141.223.181.149:8383/measurement_types
  vnfs_uri: http://141.223.181.149:8383/vnfinstances
ni_nfvo:
  host: http://141.223.181.149:8181           # Configure here to interact with an NFVO module
ni_auto_scaling:
  host: http://141.223.124.19:8005            # Configure here to interact with an Auto_scaling module
ni_orchestration:
  host: http://141.223.124.19:8009            # Configure here to interact with an Orchestration module
ni_traffic_gen:
  host: http://141.223.124.19:8010            # Configure here to interact with an Traffic generation module
ni_migration:
  host: http://141.223.124.19:8011            # Configure here to interact with an Migration Module
openstack_controller:
  ip: 141.223.181.159
  username: stack
  password: cjdakfnemfRo
  auth_api_uri: http://141.223.181.159/identity/v3/auth/tokens?nocatalog
  compute_api_uri: http://141.223.181.159/compute/v2.1
instance:                                   # Information of new instance created by a scale-out action
  username: ubuntu                                # SSH ID of new VNF instance
  password: dpnm                        # SSH ID of new VNF instance
  prefix_splitter: '-'                      # Prefix to classify VNF instance name
  max_number: 5                             # Maximum number of VNF instances allowed in each tier
  min_number: 1                             # Minimum number of VNF instances allowed in each tier
traffic_controller:                          # To access traffic controller (not generater. traffic is generated by each client vnf of sfcs)
  ip: 141.223.181.196                      # IP of traffic generator (instance in OpenStack)
  id: eaef5fab-51d4-48d7-99e1-9cce7e439afd # ID of traffic generator (instance in OpenStack) # ID of client
  username: ubuntu                            # SSH ID of traffic generator
  password: dpnm                          # SSH PW of traffic generator
  num_requests: 10                         # Number of messages (This module generates HTTP messages)
  ping_file: /home/ubuntu/ping.txt
  nping_file: /home/ubuntu/nping.txt
  ping_interval: 0.1
  tail_last_n: 100
image:                                      # Image IDs used by OpenStack
  client: 32a618a3-a324-4216-ba51-ef06ca9cfd23
  firewall: 15e16656-0e93-4593-9726-9195ba2babe3
  flowmonitor: a458f634-958a-4182-8d4b-115a7b4c4006
  dpi: 381f99c8-536d-4915-aad7-8fd974fcbabd
  ids: 414aafa2-1380-4499-bbde-f5f8caf75cf5
  proxy: 92e7b3f3-bb91-4980-a20a-0a802f332dd1
  server: e6b5f4b4-5459-48ec-8b7e-a5423b1926d1
  base: 5aa76eb9-8ba6-48af-a0d6-5874945a78af
flavor:                                     # Flavor ID used by OpenStack
  default: 75626b49-356a-4055-af32-ecbd41b03df8
shared_host:
  host1:
    ip: 141.223.181.155
    name: ni-compute-181-155
  host2:
    ip: 141.223.181.156
    name: ni-compute-181-156
# server vm to be migrated between host1 and host2
migration_test_vm:
  ip: 10.10.20.213
  username: ubuntu
  password: dpnm
  name: Migration-test-VM
  id: 5027bbd2-b085-46cc-8f4a-2545b4f9181f
  instance_name: instance-00002566

