---
swagger: "2.0"
info:
  description: "NI Conosolidation Module for the NI project."
  version: "1.0.0"
  title: "NI Conosolidation Module"
tags:
- name: "ni_consolidation_module"
  description: "Perform management decisions using ML algorithms."
schemes:
- "https"
- "http"
paths:
  /learn_consolidation:
    get:
      tags:
      - "Conosolidation APIs"
      summary: "learn_consolidation"
      operationId: "learn_consolidation"
      produces:
      - "application/json"
      parameters:
      - name: "mode"
        in: "query"
        description: "AI model"
        required: false
        type: "string"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "server.controllers.default_controller"
  /do_consolidation:
    get:
      tags:
      - "Conosolidation APIs"
      summary: "Do consolidation using AI model"
      operationId: "do_consolidation"
      produces:
      - "application/json"
      parameters:
      - name: "mode"
        in: "query"
        description: "AI model"
        required: false
        type: "string"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "server.controllers.default_controller"
  /get_busy_vnfs:
    get:
      tags:
      - "Conosolidation APIs"
      summary: "check busy VNFs from openstack and migration module"
      operationId: "get_busy_vnfs"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success."
          schema:
            type: "array"
      x-swagger-router-controller: "server.controllers.default_controller"
  /get_all_consolidation:
    get:
      tags:
      - "Conosolidation APIs"
      summary: "Get all consolidation processes that are currently active"
      operationId: "get_all_consolidation"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ConsolidationInfo"
      x-swagger-router-controller: "server.controllers.default_controller"
  /get_consolidation/{name}:
    get:
      tags:
      - "Conosolidation APIs"
      summary: "Get an active Consolidation process"
      operationId: "get_consolidation"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "The name of the consolidation"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
          schema:
            $ref: "#/definitions/ConsolidationInfo"
      x-swagger-router-controller: "server.controllers.default_controller"
  /delete_consolidation/{name}:
    delete:
      tags:
      - "Conosolidation APIs"
      summary: "Delete a consolidation process"
      description: ""
      operationId: "delete_consolidation"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "consolidation name"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "server.controllers.default_controller"
definitions:
  ConsolidationInfo:
    type: "object"
    properties:
      name:
        type: "string"
      active_flag:
        type: "boolean"
      model:
        type: "string" 
      nodes:
        type: "array"
        items:
          type: "string"
      is_trained:
        type: "boolean"
externalDocs:
  description: "Find out more about DPNM NI."
  url: "http://dpnm.postech.ac.kr/"
